### ISSUE TITLE
Missing Json file

### ISSUE THREAD

**Issue by chuck189** [DPO-Group/DPO_OpenCart#4]
Hi DPO amazing Team,

I was configuring the OpenCart and wanted to install via the dashboard installer, It failed as its saying its warning missing json file.

Regards
![Uploading Screenshot 2023-12-07 at 2.04.24 PM.png…]()

**Comment by bruce-atkinson** [comment]
@chuck189 please kindly re-attach the image?

**Comment by chuck189** [comment]
<img width="1435" alt="Screenshot 2023-12-07 at 2 04 24 PM" src="https://github.com/DPO-Group/DPO_OpenCart/assets/64158289/c2aaaaee-5cac-4367-a8b9-d02f15189e80">

**Comment by chuck189** [comment]
Hi @appinlet, Kindly find attached

**Comment by bruce-atkinson** [comment]
Hi @chuck189,

Please confirm you uploaded **dpo-opencartv1-0-1-x.ocmod.zip**, which is inside the zip **OpenCart_3.0.3.7_DPO_Plugin_1.0.1.zip** available for download at https://github.com/DPO-Group/DPO_OpenCart/releases/tag/v1.0.1

**Comment by chuck189** [comment]
Hi @appinlet,

Thanks very much appinlet i will do as wise.

Regards
